name: ci

on:
  push:
    branches:
      - documentation
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    # if: github.repository == github.event.repository.full_name
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project (src layout)
        run: uv pip install -e .

      - name: Install Documentation Dependencies
        run: uv pip install --group docs

      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
